version: "3"

services:
  web:
    build: .
    #image: "nathanaelassis/myfirstapp:2.0"
    networks:
      labdocker:
        ipv4_address: 172.14.0.2
    ports:
      - "80:80"
    environment: 
      - MESSAGE="Usando variavel de ambiente para mudar a mensagem do site!"

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "/srv/redis/data:/data"
    command: "redis-server --appendonly yes"
    networks:
      labdocker:
        ipv4_address: 172.14.0.3

networks:
  labdocker:
    ipam:
      config:
        - subnet: 172.14.0.0/24
