apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfirstapp
  labels:
    app: myfirstapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myfirstapp
  template:
    metadata:
      labels:
        app: myfirstapp
    spec:
      containers:
      - name: web
        image: gcr.io/impacta-327522/myfirstapp:2.0
        env:
        - name: REDIS_HOST
          value: 127.0.0.1
        - name: MESSAGE
          value: "Nathanael Assis - New-Generation Virtualization [Usando variavel de ambiente]"
        ports:
        - name: http
          containerPort: 80
      - name: redis
        image: redis
        ports:
        - name: redis
          containerPort: 6379
